---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
spec:
  timeout: 5m
  interval: 15m
  chart:
    spec:
      chart: istiod
      # version: latest
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 5m
  releaseName: istiod
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: disabled
  dependsOn:
      - name: istio-base
  values:
