---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: playground-local-gateway
spec:
  selector:
    istio: gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "playground.local"
        - "www.playground.local"
        - "api.playground.local"
        - "grafana.playground.local"
        - "prometheus.playground.local"
