---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kind-local-http-route
spec:
  parentRefs:
    - name: kind-local-gateway
      namespace: istio-gateway
  hostnames:
    - "kind.local"
  rules:
    - backendRefs:
      - name: istio-gateway
        port: 80
