---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: playground-local-http-route
spec:
  parentRefs:
    - name: playground-local-gateway
      group: gateway.networking.k8s.io
      kind: Gateway
      namespace: istio-gateway
      sectionName: http
  hostnames:
    - "playground.local"
    - "www.playground.local"
    - "api.playground.local"
    - "grafana.playground.local"
    - "prometheus.playground.local"
    - "rollouts.playground.local"
  rules:
    - filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            add:
              - name: x-test-header
                value: josh
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            add:
              - name: x-test-header
                value: josh
      backendRefs:
        - name: istio-gateway
          port: 80
