---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: playground-local-http-route
spec:
  parentRefs:
    - name: playground-local-gateway
      namespace: istio-gateway
  hostnames:
    - "playground.local"
  rules:
    - filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            add:
              - name: x-my-header
                value: foo
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            add:
              - name: x-my-header
                value: foo
      backendRefs:
        - name: istio-gateway
          port: 80
