---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: playground-local-gateway
spec:
  gatewayClassName: cloud-provider-kind
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "playground.local"
      allowedRoutes:
        namespaces:
          from: Same
