---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-gateway
spec:
  timeout: 5m
  interval: 15m
  chart:
    spec:
      chart: gateway
      # version: latest
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 5m
  releaseName: istio-gateway
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: disabled
  # dependsOn:
  #   - name: istio/istio-base
  #   - name: istio/istiod
  values:
    service:
      type: "ClusterIP"
