# service:
#   type: "LoadBalancer"
#   annotations:
#     metallb.universe.tf/address-pool: playground-pool
service:
  type: "ClusterIP"
# nodeSelector:
#   ingress-ready: "true"

# tolerations:
#   - key: "node-role.kubernetes.io/control-plane"
#     operator: "Equal"
#     effect: "NoSchedule"
